"""adicionar data a transacao

Revision ID: 712a4387888a
Revises: e797d9d90206
Create Date: 2026-08-12 19:05:08.838795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712a4387888a'
down_revision: Union[str, Sequence[str], None] = 'e797d9d90206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacoes', sa.Column('data', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transacoes', 'data')
    # ### end Alembic commands ###
